In [25]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [26]:
pip install matplotlib


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\inder\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\inder\appdata\local\programs\python\python312\lib\site-packages (1.26.4)




[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [5]:
y = np.array([[5,6,7],[8,9,10]])
y

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [13]:
a_range = np.arange(0,10,2)
a_range

array([0, 2, 4, 6, 8])

In [14]:
constant_array = np.full((2,2),7)
constant_array

array([[7, 7],
       [7, 7]])

In [15]:
linspace_array = np.linspace(0,1,5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
random_array = np.random.rand(2,3)
random_array

array([[0.68780141, 0.78649729, 0.72867629],
       [0.34637861, 0.64511799, 0.46161647]])

In [17]:
normal_array = np.random.randn(2,2)
normal_array

array([[ 0.58921228,  0.26109119],
       [ 0.60505008, -0.28477451]])

In [18]:
integer_array = np.random.randint(1,10, size=(2,3))
integer_array

array([[8, 6, 2],
       [1, 2, 4]])

In [19]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
diagonal_array = np.diag([1,2,3])
diagonal_array

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
zeros_like_array = np.zeros_like(diagonal_array)
zeros_like_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
ones_like_array = np.ones_like(diagonal_array)
ones_like_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
a = np.array([[[1,2,3,4],[5,6,7,8],[9,1,2,3]]])

a.ndim
a.itemsize
a.size

12

In [8]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [23]:
b = np.arange(10).reshape(5,2)
bo = np.zeros((2,3), dtype = float)
bp = np.ones((2,3))
bo
bp

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
r = np.random.random((3,4))
r

array([[0.91862959, 0.04854839, 0.25148646, 0.5957059 ],
       [0.9459759 , 0.2402144 , 0.28775808, 0.40042428],
       [0.41820856, 0.62230652, 0.01205622, 0.84953679]])

In [36]:
mix = np.arange(1,10).reshape(3,3)
mixed= np.random.randint(0,10, size = 16).reshape(4,4)
mixed


array([[0, 4, 7, 0],
       [6, 8, 8, 6],
       [2, 3, 7, 0],
       [7, 1, 3, 5]])

In [39]:
time = np.linspace(1,10,90)

time

array([ 1.        ,  1.1011236 ,  1.20224719,  1.30337079,  1.40449438,
        1.50561798,  1.60674157,  1.70786517,  1.80898876,  1.91011236,
        2.01123596,  2.11235955,  2.21348315,  2.31460674,  2.41573034,
        2.51685393,  2.61797753,  2.71910112,  2.82022472,  2.92134831,
        3.02247191,  3.12359551,  3.2247191 ,  3.3258427 ,  3.42696629,
        3.52808989,  3.62921348,  3.73033708,  3.83146067,  3.93258427,
        4.03370787,  4.13483146,  4.23595506,  4.33707865,  4.43820225,
        4.53932584,  4.64044944,  4.74157303,  4.84269663,  4.94382022,
        5.04494382,  5.14606742,  5.24719101,  5.34831461,  5.4494382 ,
        5.5505618 ,  5.65168539,  5.75280899,  5.85393258,  5.95505618,
        6.05617978,  6.15730337,  6.25842697,  6.35955056,  6.46067416,
        6.56179775,  6.66292135,  6.76404494,  6.86516854,  6.96629213,
        7.06741573,  7.16853933,  7.26966292,  7.37078652,  7.47191011,
        7.57303371,  7.6741573 ,  7.7752809 ,  7.87640449,  7.97

In [41]:
iden = np.identity(4)
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
# Scalar - learning rate
learning_rate = np.array(0.01)   # Scalar

# Vector - feature vector for ML model
features = np.array([1200, 3, 2])  # [sqft, bedrooms, bathrooms]

print("Learning rate:", learning_rate, "| ndim:", learning_rate.ndim)
print("Features:", features, "| ndim:", features.ndim)
print(features)


Learning rate: 0.01 | ndim: 0
Features: [1200    3    2] | ndim: 1
[1200    3    2]


In [51]:

# np.zeros((2, 3))       
# np.ones((2, 3))        
np.full((2, 3), 7)     
# np.identity(3)              
# np.arange(0, 10, 2)    
np.linspace(0, 1, 5)   
# np.random.rand(2, 2) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [55]:
b = np.array([1,2,3,4])
np.mean(b)
np.exp(b)
for i in b:
    print(i)

1
2
3
4
